title: Movie Review and Rating Platform
theme: jekyll-theme-primer

exclude:
  - node_modules
  - frontend/node_modules
  - backend/node_modules
  - vendor
  - package.json
  - package-lock.json
  - yarn.lock
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - frontend/build
  - frontend/dist
  - backend/build
  - backend/dist